### add product to cart
POST localhost:9998/cart
Content-Type: application/json

{
  "productId": 14,
  "quantity": 1
}

### remove product by id
PUT localhost:9998/cart/13
Content-Type: application/json

### show cart
GET localhost:9998/cart
Content-Type: application/json
