### create category Phones and Tablets
POST localhost:9998/category
Content-Type: application/json

{
    "name": "Phones and Tablets"
}

### create category Computers
POST localhost:9998/category
Content-Type: application/json

{
    "name": "Computers"
}

### create category Other
POST localhost:9998/category
Content-Type: application/json

{
    "name": "Other"
}

### get all categories
GET localhost:9998/category/all
Content-Type: application/json

### get category by id
GET localhost:9998/category/1
Content-Type: application/json