### add new discount
POST localhost:9998/discount
Content-Type: application/json

{
  "title": "Helloween Discount",
  "discountPercentage": 13,
  "startAt": "2022-10-01T00:00:00.000Z",
  "endAt": "2022-11-01T00:00:00.000Z"
}

### add new discount 2
POST localhost:9998/discount
Content-Type: application/json

{
  "title": "Xmas Discount",
  "discountPercentage": 15,
  "startAt": "2022-12-01T00:00:00",
  "endAt": "2023-01-01T00:00:00"
}

### add new discount
POST localhost:9998/discount
Content-Type: application/json

{
  "title": "Niceeeee Discount",
  "discountPercentage": 3,
  "startAt": "2022-12-01T00:00:00",
  "endAt": "2023-01-01T00:00:00"
}

### edit
PUT localhost:9998/discount/5
Content-Type: application/json

{
  "title": "Mega Coool Discount",
  "discountPercentage": 7,
  "startAt": "2022-02-01T00:00:00",
  "endAt": "2023-01-01T00:00:00"
}

### get discount by id
GET localhost:9998/discount/1

### get all discounts
GET localhost:9998/discounts
