### login into admin profile
POST localhost:9998/user/login
Content-Type: application/json

{
  "email": "alex4o@abv.bg",
  "password": "asd4!ASDa"
}

### login acc with orders and favorites
POST localhost:9998/user/login
Content-Type: application/json

{
  "email": "ivan@abv.bg",
  "password": "123456Az"

}

### login acc with nothing
POST localhost:9998/user/login
Content-Type: application/json

{
  "email": "test@abv.bg",
  "password": "123Test"

}

### logout
POST localhost:9998/user/logout
Content-Type: application/json



### product image upload
POST localhost:9998/product/5/uploadImage