### login into admin profile
POST localhost:9998/user/login
Content-Type: application/json

{
  "email": "alex4o@abv.bg",
  "password": "asd4!ASDa"

}


### adding product
POST localhost:9998/product
Content-Type: application/json

{
  "name": "Galaxy A12",
  "brand": "Samsung",
  "subcategoryId": 1,
  "price": 280,
  "info": "Very good budget phone",
  "discountId": 1
}

### adding product
POST localhost:9998/product
Content-Type: application/json

{
  "name": "Galaxy A70",
  "brand": "Samsung",
  "subcategoryId": 1,
  "price": 400,
  "info": "Not bad phone",
  "discountId": 0
}

### delete product
DELETE localhost:9998/product/7


### adding discount to product
POST localhost:9998/product/7/discount/6
Content-Type: application/json

### add attribute to product
POST localhost:9998/product/4/addattribute/1
Content-Type: application/json

{
  "value": "1"
}