### adding product
POST localhost:9998/product
Content-Type: application/json

{
  "name": "Galaxy A12",
  "brand": "Samsung",
  "subcategoryId": 1,
  "price": 280,
  "info": "Very good budget phone",
  "discountId": null
}

### adding product
POST localhost:9998/product
Content-Type: application/json

{
  "name": "Galaxy A70",
  "brand": "Samsung",
  "subcategoryId": 1,
  "price": 400,
  "info": "Not bad phone",
  "discountId": 0
}

### delete product
DELETE localhost:9998/product/12
Content-Type: application/json

### get product by id
GET localhost:9998/product/8
Content-Type: application/json

### adding discount to product
POST localhost:9998/product/10/discount/6
Content-Type: application/json

### add attribute to product
POST localhost:9998/product/12/attribute/3
Content-Type: application/json

{
  "value": "1"
}

### remove attribute from product
DELETE localhost:9998/product/4/attribute/1
Content-Type: application/json


### product search by filter
GET localhost:9998/product/search
Content-Type: application/json

{
  "subcategoryId": 1,
  "listOfBrands": [
    "Samsung",
    "Huawei"
  ],
  "min": 0.0,
  "max": 1000.0,
  "onDiscount": false,
  "attributeFilterDTOList": [
    {
      "name": null,
      "value": null
    },
    {
      "name": null,
      "value": null
    }
  ],
  "orderBy": null
}

### product search by filter
GET localhost:9998/product/search
Content-Type: application/json

{
  "subcategoryId": 1,
  "listOfBrands": [
  ],
  "min": 0.0,
  "max": 1000.0,
  "onDiscount": false,
  "attributeFilterDTOList": [
  ],
  "orderBy": "DESC"
}


### product search by keywords
GET localhost:9998/product/search/keywords
Content-Type: application/json

{
  "keywords": [
    "Samsung",
    "GalaxY",
    "A700"
  ]
}