### add review
POST localhost:9998/product/4/review
Content-Type: application/json

{

  "alias" : "Ivancho",
  "comment" : "abe ok e",
  "rating": 3,
  "isRecommended": false

}


### add review
POST localhost:9998/product/4/review
Content-Type: application/json

{

  "alias" : "Gosho",
  "comment" : "mrazq go",
  "rating": 1,
  "isRecommended": false

}

### get reviews of product
GET localhost:9998/product/4/reviews
Content-Type: application/json

### get reviews by user
GET localhost:9998/user/reviews
Content-Type: application/json