### create subcategory Phones
POST localhost:9998/subcategory
Content-Type: application/json

{
  "name": "Phones",
  "categoryId": 1
}

### create subcategory Tablets
POST localhost:9998/subcategory
Content-Type: application/json

{
  "name": "Tablets",
  "categoryId": 1
}

### create subcategory GSM
POST localhost:9998/subcategory
Content-Type: application/json

{
  "name": "GSM",
  "categoryId": 1
}

### get all subcategories
GET localhost:9998/subcategory/all
Content-Type: application/json

### get subcategory by id
GET localhost:9998/subcategory/1
Content-Type: application/json

### add attribute to subcategory
POST localhost:9998/subcategory/1/addatribute/2
Content-Type: application/json