###Registration Ivan

POST localhost:9998/user/registration
Content-Type: application/json

{
    "firstName": "Ivan",
    "lastName": "Atanasov",
    "email": "ivan@abv.bg",
    "password": "123456Az",
    "confirmPassword": "123456Az",
    "address": "Sofia, mladost4",
    "phone": "0889224499",
    "dateOfBirth": "1997-01-01",
    "male": true,
    "subscribed": true
}

### getUserById
GET localhost:9998/user/20

### edit of logged user
PUT localhost:9998/user/info
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Atanasov",
  "address": "Sofia, mladost2",
  "phone": "0889224499",
  "dateOfBirth": "1997-01-01",
  "male": true
}

### change password of logged user
PUT localhost:9998/user/info/changepassword
Content-Type: application/json

{
  "password": "123456Az",
  "newPassword": "Az123456",
  "confirmNewPassword": "Az123456"
}


### register user for delete
POST localhost:9998/user/registration
Content-Type: application/json

{
  "firstName": "Ivancho",
  "lastName": "Kalpazancho",
  "email": "ivan4oo@abv.bg",
  "password": "123456Az",
  "confirmPassword": "123456Az",
  "address": "Plovdiv, Kapana",
  "phone": "0927889182",
  "dateOfBirth": "2001-01-01",
  "subscribed": false,
  "male": true
}

### login into soon to be deleted user
POST localhost:9998/user/login
Content-Type: application/json

{
  "email": "ivan4oo@abv.bg",
  "password": "123456Az"

}

### delete user
DELETE localhost:9998/user
Content-Type: application/json

{
  "password": "123456Az",
  "confirmPassword": "123456Az"
}

### add product to favourites
POST localhost:9998/user/favourites/4
Content-Type: application/json

### get all favourite products
GET localhost:9998/user/favourites
Content-Type: application/json

### get all orders
GET localhost:9998/user/orders
Content-Type: application/json